version: "3"

services:
  loconotion:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: loconotion:latest
    volumes:
      - ./dilawars.me:/app/loconotion/dist
    restart: always
